@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col p-3">
{{--<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cursus mattis molestie a iaculis. Vestibulum lorem sed risus ultricies. Ultrices neque ornare aenean euismod elementum nisi quis. Varius quam quisque id diam vel quam elementum. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Tortor id aliquet lectus proin nibh nisl condimentum id venenatis. Varius vel pharetra vel turpis nunc eget lorem. Et odio pellentesque diam volutpat. Proin libero nunc consequat interdum varius. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Amet est placerat in egestas erat imperdiet sed. Turpis massa sed elementum tempus egestas sed. Non sodales neque sodales ut etiam sit amet nisl. Ut faucibus pulvinar elementum integer enim. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. </p>--}}

{{-- <p>Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Nulla aliquet porttitor lacus luctus accumsan tortor. Vivamus arcu felis bibendum ut tristique. Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices. Viverra maecenas accumsan lacus vel facilisis volutpat est velit. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Nulla facilisi cras fermentum odio eu feugiat. Tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Neque volutpat ac tincidunt vitae semper quis. Ipsum consequat nisl vel pretium lectus quam id. Id diam maecenas ultricies mi eget mauris pharetra et. Sapien nec sagittis aliquam malesuada bibendum arcu. Mattis nunc sed blandit libero. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa.</p>--}}

{{--<p> Viverra justo nec ultrices dui sapien eget mi proin. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Commodo odio aenean sed adipiscing diam. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Pretium aenean pharetra magna ac placerat vestibulum lectus mauris. Quis lectus nulla at volutpat diam ut venenatis. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Eget gravida cum sociis natoque penatibus et magnis. Amet nisl purus in mollis nunc sed id semper. Duis convallis convallis tellus id interdum velit laoreet id donec. Scelerisque eu ultrices vitae auctor eu augue ut lectus arcu. Cursus metus aliquam eleifend mi. Nullam vehicula ipsum a arcu cursus. </p>--}}

{{--  <p>Vulputate ut pharetra sit amet aliquam id diam maecenas. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Orci a scelerisque purus semper eget duis at tellus. Posuere urna nec tincidunt praesent. Sed pulvinar proin gravida hendrerit lectus a. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Leo vel orci porta non pulvinar neque laoreet suspendisse. Adipiscing tristique risus nec feugiat in fermentum posuere urna. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Eu nisl nunc mi ipsum faucibus vitae aliquet. Ante metus dictum at tempor commodo ullamcorper. Odio eu feugiat pretium nibh ipsum consequat nisl vel. Elementum nibh tellus molestie nunc non blandit massa enim nec. Diam ut venenatis tellus in. Congue eu consequat ac felis donec et odio. Augue ut lectus arcu bibendum at varius. Praesent elementum facilisis leo vel fringilla est ullamcorper. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. </p>--}}
{{-- <p>Netus et malesuada fames ac turpis. Etiam dignissim diam quis enim lobortis. Dui ut ornare lectus sit amet est. Aliquet risus feugiat in ante metus dictum at tempor. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Vestibulum lectus mauris ultrices eros in cursus turpis. Accumsan in nisl nisi scelerisque eu. Ullamcorper a lacus vestibulum sed arcu non odio. Velit sed ullamcorper morbi tincidunt ornare. Et tortor consequat id porta nibh. Sit amet nisl purus in mollis nunc sed. At auctor urna nunc id cursus metus aliquam eleifend. Et molestie ac feugiat sed lectus vestibulum. Mi sit amet mauris commodo. Erat imperdiet sed euismod nisi porta.</p>--}}
        </div>
    </div>
@endsection
